### ISSUE TITLE
Unable to define new variables

### ISSUE THREAD

**Issue by jwoertink** [alidavut/locus#12]
First off, this is amazing! I'm trying to debug an electron app, and the built in debugger sucks and crashes all the time. The pryjs package won't load at all. I installed this, and it did exactly what I expected right away. 

Now, when I try to define a new variable in the console (like you can with pry), I just get undefined returns.

```node
ʆ: var i = 0;
undefined
ʆ: i
ReferenceError: i is not defined
```

**Comment by alidavut** [comment]
it's really hard to make this change for now. Maybe you can use it without using ```var``` like ```i=0```.
