### ISSUE TITLE
Consider replacement for sync-prompt?

### ISSUE THREAD

**Issue by thom-nic** [alidavut/locus#8]
This looks great (I love and dearly rely on `binding.pry` in ruby.  However as far as I can tell, `sync-prompt` has build issues with node 0.11, 0.12 and iojs 1.8.1.  So it's sort of a barrier to use.  Thanks.

Related issues:
shovon/sync-prompt#11
shovon/sync-prompt#15

**Comment by OJFord** [comment]
+1. This was exactly the tool I'm looking for, but it's unfortunately unusable as-is.

**Comment by eppsilon** [comment]
@OJFord Could try the branch from this PR: https://github.com/shovon/sync-prompt/pull/17

**Comment by alidavut** [comment]
replaced with readline, update the version
