### ISSUE TITLE
Autocompletion Support

### ISSUE THREAD

**Issue by mdibaiee** [alidavut/locus#9]
Hey,

I think it's possible and useful to add autocompletion to locus, I really like the idea, a true debugging assistant.

I'm a little busy with a few open-source projects and some other work, but I will definitely take a look, what do you think @alidavut?

**Comment by alidavut** [comment]
Of course it's a good idea but I don't know that accessing variables in a scope is possible. Need to investigate.

**Comment by mdibaiee** [comment]
We might want to enable it for functions / global variables of node environment first, then we can do something about that one.
